import axios from "axios";


// createOrder (POST)
axios
    .post("http://localhost:8080/api/orders", {
        "customerId": "1",
        "cartItems": [
            {
                "productId": "123",
                "quantity": "1"
            },
            {
                "productId": "456",
                "quantity": "2"
            }
        ],
        "orderDate": "2025-07-10T12:30"
    })
    .then((response: { data: any; }) => {
        console.log(response.data)
    })
    .catch((error: any) => {
        console.error(error)
    })

// getOrderById (GET)
axios
    .get("http://localhost:8080/api/orders/customer/1")
    .then((response: { data: any; }) => {
        console.log(response.data)
    })
    .catch((error: any) => {
        console.error(error)
    })

// getAllOrders (GET)
axios
    .get("http://localhost:8080/api/orders")
    .then((response: { data: any; }) => {
        console.log(response.data)
    })
    .catch((error: any) => {
        console.error(error)
    })

// updateOrder (PUT)
const updatedOrder = {
    "customerId": "1",
        "cartItems": [
            {
                "productId": "123",
                "quantity": "2"
            },
            {
                "productId": "456",
                "quantity": "2"
            }
        ],
        "orderDate": "2025-07-10T12:30"
}
axios
    .put("http://localhost:8080/api/orders/68705ae09a8f5bec5795a144", updatedOrder) // orderId from mongoDB autogenerated
    .then((response: { data: any; }) => {
        console.log(response.data)
    })
    .catch((error: any) => {
        console.error(error)
    })

// deleteOrder (DELETE)
axios
    .delete("http://localhost:8080/api/orders/68705ae09a8f5bec5795a144")
    .then((response: { data: any; }) => {
        console.log(response.data)
    })
    .catch((error: any) => {
        console.error(error)
    })