import axios from "axios";
import { orderData } from "@/model/Orders";


// createOrder (POST)
axios
    .post<orderData>("https://cg0jnzdv-8080.usw2.devtunnels.ms/api/orders", {
        "customerId": "1",
        "items": [
            {
                "productId": "123",
                "quantity": 1
            },
            {
                "productId": "456",
                "quantity": 2
            }
        ],
        "orderDate": "2025-07-10T12:30"
    })
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })

// findByCustomerId (GET)
axios
    .get<orderData>("https://cg0jnzdv-8080.usw2.devtunnels.ms//api/orders/customer/1")
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })

// getOrderById
axios
    .get<orderData>("https://cg0jnzdv-8080.usw2.devtunnels.ms/api/orders/orderId/687999df9a8f5bec5795a17d")
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })

// getAllOrders (GET)
axios
    .get<orderData>("https://cg0jnzdv-8080.usw2.devtunnels.ms/api/orders")
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })

// updateOrder (PUT)
const updatedOrder = {
    "customerId": "1",
        "items": [
            {
                "productId": "123",
                "quantity": 2
            },
            {
                "productId": "456",
                "quantity": 2
            }
        ],
        "orderDate": "2025-07-10T12:30"
}
axios
    .put<orderData>("https://cg0jnzdv-8080.usw2.devtunnels.ms/api/orders/687999df9a8f5bec5795a17d", updatedOrder) // orderId from mongoDB autogenerated
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })

// deleteOrder (DELETE)
axios
    .delete("https://cg0jnzdv-8080.usw2.devtunnels.ms/api/orders/687999df9a8f5bec5795a17d")
    .then((response) => {
        console.log(response.data)
    })
    .catch((error) => {
        console.error(error)
    })